<center>
    <h1> ILI286 - Computación Científica II  </h1>
    <h2> Valores y Vectores Propios </h2>
    <h2> [[S]cientific [C]omputing [T]eam](#acknowledgements)</h2>
    <h2> Version: 1.12</h2>
</center>

# Tabla de Contenidos
* [Introducción](#intro)
* [Marco Teórico](#teo)
* [Algoritmos e Implementaciones](#alg)
    * [Power Iteration](#pi)
    * [Inverse Power Iteration](#invpi)
    * [Rayleigh Quotient Iteration](#rq)
    * [SciPy Eigenvalue](#sp)
    * [Problema de Aplicación](#problema)
* [Acknowledgements](#acknowledgements)

<div id='intro' />
# Introducción

Determinar los valores y vectores propios de una matriz, aporta gran información acerca de las características y propiedades de esta, como también posee gran cantidad de aplicaciones prácticas como: Análisis de convergencia de sistemas dinámicos, PCA (Principal Component Analysis), análisis espectral, Eigenfaces, etc.

Sin embargo la determinación de los valores y vectores propios no es un problema simple. Como ya debe haber estudiado en cursos anteriores, existe un método directo basado en cálculo de las raíces del polinomio característico $p(x)$. Pero este problema resulta ser _mal condicionado_, esto es, a pequeñas variaciones en la matriz $A$ original, existe una gran variación en los resultados de los valores y vectores propios obtenidos (Ver polinomio de Wilkinson, texto guia).

En este notebook estudiaremos un método iterativo conocido como _Power Iteration_ (y sus extensiones), que de modo similar a una iteración de punto fijo, permite obtener numéricamente los eigen(valores/vectores).

<div id='teo' />
# Marco Teórico

La motivación tras PI (Power Iteration) es que la multiplicación por matrices, tiende a "dirigir" a los vectores hacia el vector propio dominante (aquel con valor propio de mayor magnitud).

El algoritmo en cuestión es como sigue:

```python
x = 'Initial guess'
for i in range n_iter:
    u = x / ||x||             #normalization step
    x = dot(A,u)              #power iteration step
    lamb = dot(u, dot(A, u))  #Rayleigh quotient
return x / ||x||
```

en donde se agrega una paso de _normalización_, para evitar que la magnitud del vector aumente sin límite, y el valor propio asociado se obtiene por medio del cociente de Rayleigh:

$$ \lambda = \frac{\mathbf{x}^*\,A\,\mathbf{x}}{\mathbf{x}^*\,\mathbf{x}} $$

Para entender porque se de esta convergencia, considere una matriz $A \in \mathbb{R}^{m \times m}$ con valores propios reales $\lambda_1, \lambda_2, \ldots, \lambda_m$ tales que $|\lambda_1| > |\lambda_2| \geq |\lambda_3| \geq \ldots \geq |\lambda_m|$, tales que los vectores propios $\{\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_m \}$ conforman una base de $\mathbb{R}^m$. Sea entonces $x_0$ el _initial guess_, este puede ser expresado como una combinación lineal de los vectores propios $\mathbf{v}_k$:

\begin{align}
A x_0 &= c_1 \,A\,\mathbf{v}_1 + \cdots + c_m \,A\,\mathbf{v}_m = c_1 \lambda_1 \mathbf{v}_1 + \cdots + c_m \lambda_m \mathbf{v}_m \\
A^2 x_0 & = c_1 \lambda_1 \,A\,\mathbf{v}_1 + \cdots + c_m \lambda_m \,A\,\mathbf{v}_m = c_1 \lambda_1^2 \mathbf{v}_1 + \cdots + c_m \lambda_m^2 \mathbf{v}_m \\
\vdots &= \vdots \\
A^k x_0 &= c_1 \lambda_1^k \mathbf{v}_1 + \cdots + c_m \lambda_m^k \mathbf{v}_m
\end{align}

Factorizando $\lambda_1^k$ del último resultado se obtiene:

$$ \frac{A^k x_0}{\lambda_1^k} = c_1 \mathbf{v}_1 + c_2 \left(\frac{\lambda_2}{\lambda_1}\right)^k \mathbf{v}_2 + \cdots + c_m \left(\frac{\lambda_m}{\lambda_1}\right)^k \mathbf{v}_m$$

Dado que $|\lambda_1|>|\lambda_i| \ \ \forall i \neq 1$, a medida que $k \rightarrow \infty$ todos los términos excepto el primero tienden a cero, con razón de convergencia $S \leq |\lambda_2/\lambda_1|$. Obteniendo como resultado un vector que es múltiplo del vector propio dominante.

**Nota**: Para más detalles revisar: _Numerical Analysis, Tymothy Sauer, Chapter 12: Eigenvalues and Singular Values_

<div id='alg' />
# Algoritmos e Implementaciones

### Librerías utilizadas durante la clase

In [1]:
import numpy as np
from scipy import linalg
from matplotlib import pyplot as plt
%matplotlib inline

### Matriz y vector de prueba

In [2]:
A = np.array([[1, 0.5],[0.5, 1]])
x = np.array([1.,0.])
A = np.array([[1., 0.5,-0.1],[0.5, 1.,10.0],[2.,3.,5.]])
x = np.array([1.,0.,0.])
print("A =\n",A)
print("x =",x)

A =
 [[ 1.   0.5 -0.1]
 [ 0.5  1.  10. ]
 [ 2.   3.   5. ]]
x = [1. 0. 0.]


<div id='pi' />
## Power Iteration 
A continuación se entrega el código del algoritmo clásico de Power Iteration. Pruebe cambiando las matrices y los parámetros del algoritmo.

In [12]:
def power_iteration(A, x, k, verbose=False):
    """
    Program 12.1 Power iteration
    Computes dominant eigenvector of square matrix
    Input: matrix A, initial (nonzero) vector x, number of steps k
    Output: dominant eigenvalue lam, eigenvector u
    """
    if verbose: print("Power Iteration Method\n%s"%('='*80))
    for j in range(k):
        u = x/np.linalg.norm(x)
        x = np.dot(A, u)
        lam = np.dot(u, x) #not really necessary to compute it at each iteration
        if verbose: print("k=%d, lambda=%+.3f, u=%s"%(j,lam,str(u.T)))
    u = x/np.linalg.norm(x)
    if verbose: print("k=%d, lambda=%+.3f, u=%s\n"%(j+1,lam,str(u.T)))
    return (lam, u)    

In [13]:
# Testing algorithm
lam, u = power_iteration(A, x, 20, verbose=True)
print("lambda = {0}".format(lam))
print("u (dominant eigenvector) = {0}".format(u))

Power Iteration Method
k=0, lambda=+1.750, u=[1. 0. 0.]
k=1, lambda=+3.022, u=[0.77339713 0.37376293 0.51201381]
k=2, lambda=+3.181, u=[0.73145955 0.5525605  0.39955452]
k=3, lambda=+3.191, u=[0.69398306 0.58198258 0.42389125]
k=4, lambda=+3.192, u=[0.68876315 0.5924392  0.41787692]
k=5, lambda=+3.192, u=[0.68640667 0.59443921 0.41891277]
k=6, lambda=+3.192, u=[0.68601533 0.59509391 0.41862417]
k=7, lambda=+3.192, u=[0.68586914 0.59523122 0.41866851]
k=8, lambda=+3.192, u=[0.68584143 0.59527296 0.41865456]
k=9, lambda=+3.192, u=[0.68583223 0.59528227 0.41865639]
k=10, lambda=+3.192, u=[0.68583032 0.59528495 0.41865571]
k=11, lambda=+3.192, u=[0.68582973 0.59528558 0.41865578]
k=12, lambda=+3.192, u=[0.6858296  0.59528575 0.41865574]
k=13, lambda=+3.192, u=[0.68582956 0.59528579 0.41865575]
k=14, lambda=+3.192, u=[0.68582956 0.5952858  0.41865575]
k=15, lambda=+3.192, u=[0.68582955 0.59528581 0.41865575]
k=16, lambda=+3.192, u=[0.68582955 0.59528581 0.41865575]
k=17, lambda=+3.192, u=[0

<div id='invpi' />
## Inverse Power Iteration

Una de las complicaciones que tiene el algoritmo anterior, es que sólo permite encontrar el valor y vectores propios dominantes. Luego ¿Cómo encontramos el resto?. Para responder esta pregunta, es necesario examinar dos propiedades importantes:

1. Los valores propios de la matriz inversa $A^{-1}$ son los recíprocos de los valores propios de $A$, es decir: $\lambda_1^{-1}, \lambda_2^{-1}, \ldots , \lambda_m^{-1}$. Los vectores propios de se mantienen inalterados.
2. Los valores propios de la matriz con _shift_ $A - sI$ son: $\lambda_1-s, \lambda_2-s, \ldots, \lambda_m-s$. Del mismo modo, los vectores propios se mantienen inalterados.

**Tarea**: Pruebe estas propiedades!

La idea es entonces realizar un shift $\widetilde{s}$ cercano a algún valor propio $s_k$, y computar PI sobre $(A - \widetilde{s}I)^{-1}$. Luego:

$$ |\lambda_k - \widetilde{s}| < |\lambda_i - \widetilde{s}| \leftrightarrow  \bigg| \frac{1}{\lambda_k - \widetilde{s}} \bigg| > \bigg| \frac{1}{\lambda_i - \widetilde{s}} \bigg| \ \ \forall i \neq k \ $$

entonces $\frac{1}{\lambda_k - \widetilde{s}}$ corresponderá con el vector propio dominante de $(A - \widetilde{s}\,I)^{-1}$. Notar que por lo enunciado en las propiedades, los vectores propios se mantienen sin alteraciones.

La idea anterior se ve reflejada en el algoritmo implementado a continuación:

In [14]:
def inverse_power_iteration(A, x, s, k, verbose=False):
    """
    Program 12.2 Inverse Power iteration
    Computes eigenvector of square matrix nearest to input s
    Input: matrix A, initial (nonzero) vector x, shift s, number of steps k
    Output: dominant eigenvalue lam, eigenvector of inv(A-sI)
    """
    if verbose: print("Inverse Power Iteration Method\n%s"%('='*80))
    As = A - s*np.eye(*A.shape)
    for j in range(k):
        u = x/np.linalg.norm(x)
        x = np.linalg.solve(As, u) # Critical line!
        lam = np.dot(u.T, x)
        if verbose: print("k=%d, lambda=%+.3f, u=%s"%(j,1./lam+s,str(u.T)))
    u = x/np.linalg.norm(x)
    if verbose: print("k=%d, lambda=%+.3f, u=%s\n"%(j+1,1./lam+s,str(u.T)))
    return (1./lam+s, u)

In [15]:
# Testing algoritm
lam, u = inverse_power_iteration(A, x, s=1./4, k=10, verbose=True)
print("lambda = {0}".format(lam))
print("v = {0}".format(u))

Inverse Power Iteration Method
k=0, lambda=+1.595, u=[1. 0. 0.]
k=1, lambda=+0.949, u=[ 0.61652105 -0.6729449   0.40871379]
k=2, lambda=+0.859, u=[ 0.72144857 -0.68240642 -0.11761564]
k=3, lambda=+0.833, u=[ 0.59475191 -0.78714248  0.16333062]
k=4, lambda=+0.824, u=[ 0.66347712 -0.74793374 -0.01983   ]
k=5, lambda=+0.821, u=[ 0.62102451 -0.77856232  0.09038397]
k=6, lambda=+0.819, u=[ 0.64740706 -0.76180395  0.02277812]
k=7, lambda=+0.819, u=[ 0.63160679 -0.77264534  0.0639691 ]
k=8, lambda=+0.819, u=[ 0.64137313 -0.76624493  0.03884856]
k=9, lambda=+0.819, u=[ 0.635472   -0.77022164  0.05416608]
k=10, lambda=+0.819, u=[ 0.63909049 -0.76782404  0.04482845]

lambda = 0.818632615669599
v = [ 0.63909049 -0.76782404  0.04482845]


<div id='rq' />
## Rayleigh Quotient Iteration

Como se analizó anteriormente, PI e _Inverse_ PI tienen convergencia lineal con razón de convergencia $S \approx \frac{\lambda_2}{\lambda_1}$. Además sabemos que _Inverse_ PI converge hacia el valor propio más cercano al shift, y que mientras más cercano sea el shift a tal valor, más rápido se logra la convergencia.

Entonces la idea de RQI es la siguiente: Si en cada iteración se tiene una aproximación del valor propio que andamos buscando, podemos ocupar esta aproximación como shift $s$, y dado que el shift será más cercano al valor propio, se acelerará la convergencia.

Tal valor aproximado es obtenido con el cociente de Rayleigh, y entonces el shift es actualizado con este cociente en cada iteración. Como resultado se produce el siguiente _trade-off_:

1. La convergencia pasa a ser cuadrática (de modo general) y cúbica para matrices simétricas.
2. Sin embargo, se paga el costo de tener que resolver un sistema de ecuaciones diferentes en cada iteración.


A continuación se presenta una implementación del RQI:

In [16]:
def rqi(A, x, k, verbose=False):
    """
    Program 12.3 Rayleigh Quotient Iteration
    Input: matrix A, initial (nonzero) vector x, number of steps k
    Output: eigenvalue lam, eigenvector of inv(A-sI)
    """
    if verbose: print("Rayleigh Quotient Iteration\n%s"%('='*80))
    for j in range(k):
        u = x/np.linalg.norm(x)
        lam = np.dot(u.T, np.dot(A, u))
        try:
            x = np.linalg.solve(A -lam*np.eye(*A.shape), u)
        except numpy.linalg.LinAlgError:
            break
        if verbose: print("k=%d, lambda=%+.3f, u=%s"%(j,lam,str(u.T)))
    u = x/np.linalg.norm(x)
    lam = float(np.dot(u.T, np.dot(A, u)))
    if verbose: print("k=%d, lambda=%+.3f, u=%s\n"%(j+1,lam,str(u.T)))
    return (lam, u)

**Preguntas:** 
1. ¿Porque es necesario el `try` y `except` en las líneas 11 y 13? ¿Que significa que el sistema no pueda ser resuelto?
2. Como puede observar RQI no recibe shift como parámetro. ¿A cuál valor/vector propio convergerá? ¿Como forzar/guiar a que tienda hacia un valor/vector propio distinto?

In [17]:
# Testing algorithm
lam, v = rqi(A, x, k=2)
print("lambda = {0}".format(lam))
print("v = {0}".format(v))

lambda = 1.0016000006830446
v = [ 0.82668162 -0.55259858  0.1059826 ]


<div id='sp' />
## $\texttt{SciPy}$ Eigenvalue
La librería scipy tiene implementados algoritmos que permite calcular los valores y vectores propios. Las opciones posibles son:

  - En la librería scipy.linalg: eigvals/eigvalsh/eigvals_banded, eig/eigh/eig_banded,

  - En la librería scipy.sparse.linalg: eigen, eigs, eigsh.
 
En general siempre conviene utilizar las funciones desde scipy y no de numpy. La librería numpy hace un excelente trabajo al permitir el uso de vectores de tipo numérico, pero contiene solo algunos algoritmos numéricos y no necesariamente los más rápidos.

A continuación se muestra como utilizar algunas de estas funciones.

In [18]:
# Full matrices
from scipy import linalg as LA
N = 3
Aux = np.random.rand(N,N)
A = Aux + Aux.T # symmetric, so we'll deal with real eigs.
print(LA.eigvals(A)) # Only the eigenvalues, A not necessarily symmetric
print("*"*80)
print(LA.eigvalsh(A)) # Only the eigenvalues, A symmetric 
print("*"*80)
print(LA.eig(A))     # All the eigenvalues and eigenvectors, A not necessarily symmetric
print("*"*80)
print(LA.eigh(A))    # All the eigenvalues and eigenvectors, A symmetric (faster)
print("*"*80)
lambdas, V = LA.eigh(A)    # All the eigenvalues and eigenvectors, A symmetric (faster)
l1 = lambdas[0]
v1 = V[:,0]
print(l1)
print(v1)
print(np.dot(A, v1))
print(l1*v1)

[ 3.31010396+0.j  0.35839548+0.j -0.77367714+0.j]
********************************************************************************
[-0.77367714  0.35839548  3.31010396]
********************************************************************************
(array([ 3.31010396+0.j,  0.35839548+0.j, -0.77367714+0.j]), array([[-0.65641459, -0.60673104, -0.44832726],
       [-0.60814465,  0.77723663, -0.16144137],
       [-0.44640785, -0.16667535,  0.8791697 ]]))
********************************************************************************
(array([-0.77367714,  0.35839548,  3.31010396]), array([[ 0.44832726,  0.60673104, -0.65641459],
       [ 0.16144137, -0.77723663, -0.60814465],
       [-0.8791697 ,  0.16667535, -0.44640785]]))
********************************************************************************
-0.7736771354578265
[ 0.44832726  0.16144137 -0.8791697 ]
[-0.34686055 -0.12490349  0.68019349]
[-0.34686055 -0.12490349  0.68019349]


<div id='problema' />
## Problema de Aplicación

Las matrices simétricas tiene una propiedad muy interesante:

* Los vectores propios de las matrices simétricas son ortogonales entre sí.

En base a lo anterior se propone el siguiente algoritmo para encontrar los primeros $k$ valores/vectores propios:

```python
def kEigenFinder(A, k, p):
    m = A.shape[0]
    lamb = 0.
    v = np.zeros((m,1))
    Lamb = []
    V = []
    for i in range(k):
        A -= lamb*np.dot(v,v.T)
        lamb,v = power_iteration(A, p)
        Lamb.append(lamb)
        V.append(v)
    return Lamb,V    
```

1. Justifique la validez de tal procedimiento.
2. Construya una matriz simétrica de $100 \times 100$ y ejecute el `kEigenFinder` sobre tal matriz. Una forma fácil de construir una matriz simétrica es la [matriz de covarianza](https://en.wikipedia.org/wiki/Covariance_matrix):
$$\Sigma_X = \frac{1}{n-1}X^T X$$
donde $X \in \mathbb{R}^{m \times n}$, con $m$ _samples_ y $n$ _features_.

3. Concluya acerca de la utilidad del procedimiento propuesto. 

<div id='acknowledgements' />
# Acknowledgements
* _Material creado por profesor Claudio Torres_ (`ctorres@inf.utfsm.cl`) _y ayudantes: Alvaro Salinas y Martín Villanueva. DI UTFSM. Abril 2016._

***
### DISCLAIMER ###

El presente notebook ha sido creado para el curso **ILI286 - Computación Científica 2**, del [Departamento de Informática](http://www.inf.utfsm.cl/), [Universidad Técnica Federico Santa María](http://www.utfsm.cl/). 

El material ha sido creado por Claudio Torres <ctorres@inf.utfsm.cl> y Sebastian Flores <sebastian.flores@usm.cl>, y es distribuido sin restricciones. En caso de encontrar un error, por favor no dude en contactarnos.

[Update 2015] Se ha actualizado los notebooks a Python3 e includio el "magic" "%matplotlib inline" antes de cargar matplotlib para que los gráficos se generen en el notebook. 

[Update 2016] (Martín) Modificaciones mayores al formato original. Agregado contexto: Introducción, marco teórico, explicaciones y tareas. Modificaciones menores en los algoritmos. Agregada la sección de Problema de Aplicación.

[Update 2018] (C.Torres) Using np.linalg.

[Update 2019] (C.Torres) Using * and mathbf for vectors.
***